package dev.talosdx.blogcms.system

import dev.talosdx.blogcms.entity.BaseStringNotAutoGeneratedIdAuditEntity
import javax.persistence.Entity
import javax.persistence.Table

@Entity
@Table(name = "system_settings")
class SystemSettings(
    id: String,
    val value : String
) : BaseStringNotAutoGeneratedIdAuditEntity(id) {
}