package dev.talosdx.blogcms.i18n

import dev.talosdx.blogcms.entity.BaseStringNotAutoGeneratedIdAuditEntity
import org.springframework.context.annotation.Lazy
import javax.persistence.*

@Entity
@Table(name = "language")
class Language(
    isoFormattedId: String,
    val isEnabled: Boolean = true,
    val isDefault: Boolean = false,
    @Lazy
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
    val translations: MutableSet<I18n> = mutableSetOf(),
) : BaseStringNotAutoGeneratedIdAuditEntity(isoFormattedId) {
}


