package dev.talosdx.blogcms.component

import dev.talosdx.blogcms.entity.BaseStringNotAutoGeneratedIdAuditEntity
import dev.talosdx.blogcms.permission.Permission
import org.springframework.context.annotation.Lazy
import javax.persistence.*

@Entity
@Table(name = "component")
class CMSComponent(
    id: String,
    var name: String = "component.$id.name",
    var description: String = "component.$id.description",
    @Lazy
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "component")
    val permissions: MutableSet<Permission> = mutableSetOf(),
) : BaseStringNotAutoGeneratedIdAuditEntity(id) {
}